language: r
matrix:
  include:
    - name: "Doc check"
      r: release
      r_packages:
        - devtools
        - roxygen2
      script:
        - ./tools/checkDocsCurrent.sh
    - name: "Old Release Check"
      r: oldrel
    - name: "Current Release Check"
      r: release
    - name: "Development Release Check"
      r: devel
sudo: false
cache: packages
notifications:
  email:
    on_success: change
    on_failure: change
